theme: minima
title: "Sports and Entertainment"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Defaults
description: ""Insightful takes on Indian Sports, Bollywood, and Global Cinema."
url: "https://https://abhayshankar2028-lab.github.io/my-blog"
author: "Abhay Shankar"

google_analytics: G-3EE5LQ6EGP
