theme: minima
title: "Sports and Entertainment"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO Defaults
description: "Insightful takes on Indian Sports, Bollywood, and Global Cinema."
url: "https://abhayshankar2028-lab.github.io"
baseurl: "/my-blog"
author: "Abhay Shankar"

# Twitter Defaults
twitter:
  username: Abhayshankar2028-lab
  card: summary_large_image

google_analytics: G-3EE5LQ6EGP
